package errorHandiling;

public class Multiple3 {
    public static void main(String[] args) {
        try{
        int arr[]= new int[5];
        }
        catch(Exception e){
        System.out.println("Exception handled");
        }
        // intelli J does not let us to write next line because exception should be written
        //specific to general
        //catch(ArithmeticException e){

    }
}
